config/routes.rb
Rails.application.routes.draw do
  resources :equip_service_calls
  resources :equip_warranty_notes
  resources :equip_notes
  resources :csas
  resources :equipment
  resources :customers
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #get 'about-me', to: 'pages#about'
  get 'home', to: 'pages#home'
  get 'updateCust', to: 'equipment#updateCust'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  acts_as_copy_target
  
end

app/models/csa.rb
class Csa < ApplicationRecord
  has_many :equipment
  has_many :customers, through: :equipment
  
  def self.by_CSA
    order("id ASC")
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :equipment
  has_many :csas, through: :equipment 
  
  def self.to_csv
    attributes = %w{id cust_id}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      
      all.each do |customer|
        csv << customer.attributes.values_at(*attributes)
      end
    end
  end
  
  def self.by_last_name
    order("last_name ASC")
  end
  
  def self.by_last_first_name
    order("last_name ASC, first_name ASC")
  end
end

app/models/equip_note.rb
class EquipNote < ApplicationRecord
  belongs_to :equipment
end

app/models/equip_service_call.rb
class EquipServiceCall < ApplicationRecord
  belongs_to :equipment
end

app/models/equip_warranty_note.rb
class EquipWarrantyNote < ApplicationRecord
  belongs_to :equipment
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :customer
  belongs_to :csa
  has_many :equip_note
  has_many :equip_warranty_note
  has_many :equip_service_call
  
  def self.byCust
    order("cust_id DESC", "id ASC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/csas_controller.rb
class CsasController < ApplicationController
  
  def new
    @csa = Csa.new
  end
 
  def index
    @csas = Csa.by_CSA
  end
  
  def show
    @csa = Csa.find((params[:id]))
    
  end
  
  def edit
    @csa = Csa.find((params[:id]))  
  end
  
  def update
    @csa = Csa.find((params[:id]))  
    respond_to do |format|
      if @csa.update(csa_params)
        format.html { redirect_to @csa, notice: 'CSA was successfully updated.' }
        format.json { render :show, status: :ok, location: @csa }
      else
        format.html { render :edit }
        format.json { render json: @csa.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
  def csa_params
      params.require(:csa).permit(:cust_id, :csa, :equip_id, :start_date, :end_date, :term, :equip_desc, :total_perks, :equipment_id)
    end
  
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :destroy]

  # GET /customers
  
  def index
    # @customers = Customer.by_last_name
    @customers = Customer.by_last_first_name
    #*************** Process for generating a csv file ****************
    #*************** Output is customers.csv in temp file
    respond_to do |format|
      format.html
      format.csv { send_data @customers.to_csv }
    end
    #************************************
  end

  # GET /customers/1
  
  def show
    # @customer = Customer.find(params[:id])
    @customer = Customer.includes(:equipment, :csas).find(params[:id])
    
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  
  def create
    
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /customers/1
  
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /customers/1
  
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
    end
  end

  private
    
    def set_customer
      @customer = Customer.find(params[:id])
    end

    
    def customer_params
      
      params.require(:customer).permit(:cust_id, :first_name, :last_name, :address1, :address2, :city, :st, :zip, :home_phone, :work_phone, :cell_phone, :email, :auto_serv, :notes)
    end
end

app/controllers/equip_notes_controller.rb
class EquipNotesController < ApplicationController
  def index
    @equip_notes = EquipNote.all
  end
end

app/controllers/equip_service_calls_controller.rb
class EquipServiceCallsController < ApplicationController
  def index
    @equip_service_calls = EquipServiceCall.all
  end
end

app/controllers/equip_warranty_notes_controller.rb
class EquipWarrantyNotesController < ApplicationController
  def index
    @equip_warranty_notes = EquipWarrantyNote.all
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.byCust
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.includes(:equip_note, :csa, :equip_warranty_note, :equip_service_call).find(params[:id])
    respond_to do |format|
      format.html { render action: "show" }
      # format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def updateCust
    @equipment = Equipment.byCust
    @customer = Customer.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:cust_id, :equip_id, :csa, :serial, :model, :manufacturer, :product_type, :date_installed, :customer_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @customers = Customer.by_last_name
    @equipment = Equipment.all
  end

  def about
    
  end

  def contact
  end
  
  def tech_news
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cs_as_helper.rb
module CsAsHelper
end

app/helpers/csas_helper.rb
module CsasHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/equip_notes_helper.rb
module EquipNotesHelper
end

app/helpers/equip_service_calls_helper.rb
module EquipServiceCallsHelper
end

app/helpers/equip_warranty_notes_helper.rb
module EquipWarrantyNotesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/csas/edit.html.erb
<h1>Editing Csa</h1>

<%= render 'form', csa: @csa %>

<%= link_to 'Show', @csa %> |
<%= link_to 'Back', csas_path %>

app/views/csas/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h2>CSA Information</h2>
  <%= link_to 'New Csa', new_csa_path %>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">ID</div>
        <div class="col-md-1">Cust_id</div>
        <div class="col-md-1">CSA_Old</div>
        <div class="col-md-1">Equip_id</div>
        <div class="col-md-1">Start Date</div>
        <div class="col-md-1">End Date</div>
        <div class="col-md-1">Term</div>
        <div class="col-md-2">Equip Desc</div>
        <div class="col-md-1">Perks</div>  
        <div class="col-md-1">Actions</div>
      </div>
    </div>
  </div>
  
  <% @csas.each do |csa| %>
    <div class="equip-card">
      <div class="equip-card-block">
        <div class = "row equip-row">
          <div class="col-md-1"><%= csa.id %></div>
          <div class="col-md-1"><%= csa.cust_id %></div>
          <div class="col-md-1"><%= csa.csa %></div>
          <div class="col-md-1"><%= csa.equip_id %></div>
          <div class="col-md-1"><%= csa.start_date %></div>
          <div class="col-md-1"><%= csa.end_date %></div>
          <div class="col-md-1"><%= csa.term %></div>
          <div class="col-md-2"><%= csa.equip_desc %></div>
          <div class="col-md-1"><%= csa.total_perks %></div> 
          <div><%= link_to 'Show', csa %></div> 
          <div><%= link_to 'Edit', edit_csa_path(csa) %></div> 
          <div><%= link_to 'Destroy', csa, method: :delete, data: { confirm: 'Are you sure?' } %></div> 
        </div>
      </div>
    </div>
  <% end %>
  
</div>


<br>

<%= link_to 'New Csa', new_csa_path %>

app/views/csas/new.html.erb
<h1>New Csa</h1>

<%= render 'form', csa: @csa %>

<%= link_to 'Back', csas_path %>

app/views/csas/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h2>CSA Information</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">ID</div>
        <div class="col-md-1">Cust_id</div>
        <div class="col-md-1">CSA_Old</div>
        <div class="col-md-1">Equip_id</div>
        <div class="col-md-1">Start Date</div>
        <div class="col-md-1">End Date</div>
        <div class="col-md-1">Term</div>
        <div class="col-md-2">Equip Desc</div>
        <div class="col-md-1">Perks</div>        
      </div>
    </div>
  </div>
  
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1"><%= @csa.id %></div>
        <div class="col-md-1"><%= @csa.cust_id %></div>
        <div class="col-md-1"><%= @csa.csa %></div>
        <div class="col-md-1"><%= @csa.equip_id %></div>
        <div class="col-md-1"><%= @csa.start_date %></div>
        <div class="col-md-1"><%= @csa.end_date %></div>
        <div class="col-md-1"><%= @csa.term %></div>
        <div class="col-md-2"><%= @csa.equip_desc %></div>
        <div class="col-md-1"><%= @csa.total_perks %></div>        
      </div>
    </div>
  </div>


<%= link_to 'Edit', edit_csa_path(@csa) %> |
<%= link_to 'Back', csas_path %>

app/views/customers/_customer_lookup.html.erb
<%= form_for(customer) do |f| %>



<div class="form-group">
    <%= f.label :cust_id, class:'col-form-label col-form-label' %>
    <%= f.collection_select(:cust_id, Customer.all, :id, :first_name,
                              {
                                #selected: blog.topic.id,
                                include_blank: true
                              },
                              class: 'col-form-label'
                            )
    %>
  </div>

<% end %>





<!--<%# end %>-->

<!--<%# @customers.each do |customer| %>-->
<!--  <div><%#= customer.id %>-->
<!--        <%#= customer.cust_id %>-->
<!--        <%#= customer.first_name %>-->
<!--        <%#= customer.last_name %>-->
<!--        <%#= link_to 'Show', customer %>-->
<!--        <%#= link_to 'Edit', edit_customer_path(customer) %>-->
<!--        <%#= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></div>  -->
<!--<%# end %>        -->

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>
<!DOCTYPE html>
<html>
<head>

<!--<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>-->
  
<!--<script>-->
<!--$(document).ready-->
<!--$(document).on('change', '.custTag', function(){-->
    
<!--    var custId = $(this).val();-->
<!--    console.log (custId);-->
<!--    $.get('/customers/' + custId);-->
    
<!--});-->

<!--</script>-->


</head>
<!--<%# @item_paths = {"Select"=>"", "CustomerA" => customer_path(6311), "CustomerB" => customer_path(8398)}%>-->
<!--<%# @add_item_paths = {"CustomerC" => customer_path(6659), "CustomerD" => customer_path(1551)}%>-->
<!--<%# @item_paths.merge!(@add_item_paths) %>-->
<!--<%#= select_tag :show_item, options_for_select(@item_paths)%>-->
<!--<p><%#= @item_paths %></p>-->

<!--hash = {:item1 => 1}-->
<!--another_hash = {:item2 => 2, :item3 => 3}-->
<!--hash.merge(another_hash)-->

<% @custPath = {"Select"=>""} %>
<% @customers.each do |customer| %>
  <% @addPath = {customer.last_name + ", " + customer.first_name => customer_path(customer.id)} %>
  <% @custPath.merge!(@addPath) %>
<% end %> 

<%= select_tag :show_item, options_for_select(@custPath)%>

<script type="text/javascript">
      $('#show_item').change(function() {
      window.location = $(this).find('option:selected').val();
      });
      
      // $('#show_item2').change(function() {
      // window.location = $(this).find('option:selected').val();
      // });
      
      // $('#show_item3').change(function() {
      // window.location = $(this).find('option:selected').val();
      // });
 </script>

<!--<#= select_tag( "cust_id", options_from_collection_for_select(@customers.by_last_name, :id, :last_name, (@customers_id.nil?) ? nil : @customers_id), {:class => 'custTag'}) %> -->


<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr class="custRow">
        <td><%= customer.id %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

</html>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <h2>Customer Information</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">ID</div>
        <div class="col-md-1">Old_ID</div>
        <div class="col-md-2">FirstName</div>
        <div class="col-md-2">LastName</div>
         
      </div>
    </div>
  </div>

  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1"><%= @customer.id %></div>
        <div class="col-md-1"><%= @customer.cust_id %></div>
        <div class="col-md-2"><%= @customer.first_name %></div>
        <div class="col-md-2"><%= @customer.last_name %></div>
              
      </div>
    </div>
  </div>

<div>
  <h2>Equipment Information</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">EquipID</div>
        <div class="col-md-1">Old_EquipID</div>
        <div class="col-md-1">Customer</div>
        <div class="col-md-1">Old CustID</div>
        <div class="col-md-1">CSA_Old</div>
        <div class="col-md-1">CSA_New</div>
        <div class="col-md-2">Serial</div>
        <div class="col-md-1">Model</div>        
      </div>
    </div>
  </div>
  <%= render @customer.equipment %>
          
</div>

<div>
  <h2>CSA Information</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">CSA ID</div>
        <div class="col-md-1">CSA-Old</div>
        <div class="col-md-1">Old EquipID</div>
        <div class="col-md-1">Old_CustID</div>
        <div class="col-md-1">Start Date</div>
        <div class="col-md-1">End Date</div>
        <div class="col-md-1">Term</div>
        <div class="col-md-1">Equip Desc</div>
        <div class="col-md-1">Perks</div>
      </div>
    </div>
  </div>
  <% if  @customer.csas.empty? %>
    <div>
      <h5>No CSA for this Customer</h>
      </div>
    <hr>
  <% else %>
    <%= render @customer.csas %>
    </div>
    <hr>
  <% end %>
  
</div>
<!--<p>-->
<!--  <strong>Address1:</strong>-->
<!--  <%= @customer.address1 %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Address2:</strong>-->
<!--  <%= @customer.address2 %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>City:</strong>-->
<!--  <%= @customer.city %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>St:</strong>-->
<!--  <%= @customer.st %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Zip:</strong>-->
<!--  <%= @customer.zip %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Home phone:</strong>-->
<!--  <%= @customer.home_phone %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Work phone:</strong>-->
<!--  <%= @customer.work_phone %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Cell phone:</strong>-->
<!--  <%= @customer.cell_phone %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Email:</strong>-->
<!--  <%= @customer.email %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Auto serv:</strong>-->
<!--  <%= @customer.auto_serv %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Notes:</strong>-->
<!--  <%= @customer.notes %>-->
<!--</p>-->


<%= link_to 'Edit Customer', edit_customer_path(@customer) %> |
<%= link_to 'Customer List', customers_path %>

app/views/equip_notes/index.html.erb
<%= @equip_notes.inspect %>

app/views/equipment/_equipment.html.erb
<div class="equip-card">
  <div class="equip-card-block">
    <div class = "row">
      <div class="col-md-1"><%= link_to equipment.id, equipment_path(equipment.id)%></div> 
      <div class="col-md-1"><%= equipment.equip_id %></div>
      <div class="col-md-1"><%= equipment.customer_id %></div>
      <div class="col-md-1"><%= equipment.cust_id %></div>
      <div class="col-md-1"><%= equipment.csa1 %></div>
      <div class="col-md-1"><%= equipment.csa_id %></div>
      <div class="col-md-2"><%= equipment.serial %></div>
      <div class="col-md-1"><%= equipment.model %></div>        
    </div>
  </div>
</div>

app/views/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<p id="notice"><%= notice %></p>
<div>
  <h2>Equipment Information</h2>
  <%= link_to 'New Equipment', new_equipment_path %>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">ID</div>
        <div class="col-md-1">Equip_id</div>
        <div class="col-md-1">Cust_id</div>
        <div class="col-md-1">Cust_Old</div>
        <!--<div class="col-md-1">CSA_ID</div>-->
        <!--<div class="col-md-1">CSA_Old</div>-->
        <div class="col-md-1">Serial</div>
        <div class="col-md-1">Model</div>
        <div class="col-md-1">Manufacturer</div>
        <div class="col-md-1">Product Type</div>
        <div class="col-md-1">InstallDate</div>  
        <div class="col-md-1">Actions</div>
      </div>
    </div>
  </div>
  
  <% @equipment.each do |e| %>
    <div class="equip-card">
      <div class="equip-card-block">
        <div class = "row equip-row">
          <div class="col-md-1"><%= e.id %></div>
          <div class="col-md-1"><%= e.equip_id %></div>
          <div class="col-md-1"><%= e.customer_id %></div>
          <div class="col-md-1"><%= e.cust_id %></div>
          <!--<div class="col-md-1"><%= e.csa_id %></div>-->
          <!--<div class="col-md-1"><%= e.csa1 %></div>-->
          <div class="col-md-1"><%= e.serial %></div>
          <div class="col-md-1"><%= e.model%></div>
          <div class="col-md-1"><%= e.manufacturer %></div>
          <div class="col-md-1"><%= e.product_type %></div> 
          <div class="col-md-1"><%= e.date_installed %></div>
          <div><%= link_to 'Show', e %></div> |
          <div><%= link_to 'Edit', edit_equipment_path(e) %></div> |
          <div><%= link_to 'Destroy', e, method: :delete, data: { confirm: 'Are you sure?' } %></div> 
        </div>
      </div>
    </div>
  <% end %>
  
</div>


<br>

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <h2>Equipment Information</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">ID</div>
        <div class="col-md-1">Old Equip_id</div>
        <div class="col-md-1">Customer ID</div>
        <div class="col-md-1">Old CustID</div>
        <div class="col-md-1">CSA</div>
        <div class="col-md-1">CSA_Old</div>
        <div class="col-md-1">Serial</div>
        <div class="col-md-1">Model</div>
        <div class="col-md-1">Manufacturer</div>
        <div class="col-md-2">Type</div>
        <div class="col-md-1">Install Date</div>        
      </div>
    </div>
  </div>
  
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1"><%= @equipment.id %></div>
        <div class="col-md-1"><%= @equipment.equip_id %></div>
        <div class="col-md-1"><%= @equipment.customer_id %></div>
        <div class="col-md-1"><%= @equipment.cust_id %></div>
        <div class="col-md-1"><%= @equipment.csa_id %></div>
        <div class="col-md-1"><%= @equipment.csa1 %></div>
        <div class="col-md-1"><%= @equipment.serial %></div>
        <div class="col-md-1"><%= @equipment.model %></div>
        <div class="col-md-1"><%= @equipment.manufacturer %></div>
        <div class="col-md-2"><%= @equipment.product_type %></div>
        <div class="col-md-1"><%= @equipment.date_installed %></div>        
      </div>
    </div>
  </div>
</div>
<hr>
<div>
  <h2>Equipment Notes</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">Note_ID</div>
        <div class="col-md-1">Equip_ID</div>
        <div class="col-md-1">Old_EquipID</div>
        <div class="col-md-1">Old_CustID</div>
        <div class="col-md-2">Notes</div>
      </div>
    </div>
  </div>
  <% if  @equipment.equip_note.empty? %>
    <div>
      <h5>No Equipment Notes for this Equipment</h>
    </div>
    <hr>
  <% else %>
    <div>
      <%= render @equipment.equip_note %>
    </div>
    <hr>
  <% end %>
</div>

<div>
  <h2>Equipment Warranty Notes</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">Note_ID</div>
        <div class="col-md-1">Equip_ID</div>
        <div class="col-md-2">Old Equip_ID</div>
        <div class="col-md-1">Old_CustID</div>
        <div class="col-md-5">Notes</div>
      </div>
    </div>
  </div>
  <% if  @equipment.equip_warranty_note.empty? %>
    <div>
      <h5>No Warranty Notes for this Equipment</h>
    </div>
    <hr>
  <% else %>
    <div>
      <%= render @equipment.equip_warranty_note %>
    </div>
    <hr>
  <% end %>
</div>  

<div>
  <h2>Service Call Notes</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">Note_ID</div>
        <div class="col-md-1">Equip_ID</div>
        <div class="col-md-2">Old Equip_ID</div>
        <div class="col-md-1">Old_CustID</div>
        <div class="col-md-5">Notes</div>
      </div>
    </div>
  </div>
  <% if  @equipment.equip_service_call.empty? %>
    <div>
      <h5>No Service for this Equipment</h>
    </div>
    <hr>
  <% else %>
    <div>
      <%= render @equipment.equip_service_call %>
    </div>
    <hr>
  <% end %>
</div>  

<div>
  <h2>CSA Information</h2>
  <div class="equip-card">
    <div class="equip-card-block">
      <div class = "row equip-row">
        <div class="col-md-1">CSA ID</div>
        <div class="col-md-1">CSA-Old</div>
        <div class="col-md-1">Old EquipID</div>
        <div class="col-md-1">Old_CustID</div>
        <div class="col-md-1">Start Date</div>
        <div class="col-md-1">End Date</div>
        <div class="col-md-1">Term</div>
        <div class="col-md-1">Equip Desc</div>
        <div class="col-md-1">Perks</div>
      </div>
    </div>
  </div>
  <% if  @equipment.csa == nil %>
    <div>
      <h5>No CSA for this Equipment</h>
      </div>
    <hr>
  <% else %>
    <%= render @equipment.csa %>
    </div>
    <hr>
  <% end %>

<%= link_to 'Edit Equipment', edit_equipment_path(@equipment) %> |
<%= link_to 'Equipment List', equipment_index_path %> |
<%= link_to 'Customers', customers_path %>